$pdf_mode = 5;  # use xelatex -> .pdf
$pdflatex = 'xelatex %O -interaction=nonstopmode -synctex=1 %S';
$xelatex = 'xelatex %O -interaction=nonstopmode -synctex=1 %S';
$ENV{PATH} = "/Library/TeX/texbin:$ENV{PATH}";
